using System;
using System.Collections.Generic;

namespace ReportesColgate.Models
{
    public partial class Scoredcard
    {
        public int IndiceSc { get; set; }
        public string Productid { get; set; }
        public string ProductNo { get; set; }
        public string Productid1 { get; set; }
        public string Item { get; set; }
        public string Subcategoria { get; set; }
        public string Anio { get; set; }
        public string Ac { get; set; }
        public string Pais { get; set; }
        public string Formato { get; set; }
        public string Nomenclatura { get; set; }
        public string Espacio { get; set; }
        public string NumeroTienda { get; set; }
        public string NombreTienda { get; set; }
        public string Categoria { get; set; }
        public string Supervisor { get; set; }
        public string Programa { get; set; }
        public string MedicionCms { get; set; }
        public string Descripcion { get; set; }
        public string VndrName { get; set; }
        public string BrandName { get; set; }
        public string CodProv { get; set; }
        public string NomProv { get; set; }
        public string Area { get; set; }
        public string Upc { get; set; }
        public string PorcentajeEspacio { get; set; }
        public string FechaInicioTienda { get; set; }
        public string FechaFinTienda { get; set; }
        public string VendorNbr { get; set; }
        public string ApoyoTienda { get; set; }
        public string CortesCaja { get; set; }
        public string ImplementacionModularCudadoOcremasDentales { get; set; }
        public string ImplementacionModularCuidadoOcepillosDentas { get; set; }
        public string ImplementacionModularCuidadoOenjaguesBucal { get; set; }
        public string ImplementacionModularCuidadoPjabonesTocad { get; set; }
        public string ImplementacionModularCuidadoPdesodorant { get; set; }
        public string ImplementacionModularCuidadoPshamp { get; set; }
        public string ImplementacionModularCuidadoHsuavisant { get; set; }
        public string ImplementacionModularLavaplat { get; set; }
        public string ImplementacionModularCuidadoHdesinfectant { get; set; }
        public string Limpieza { get; set; }
        public string TiendaRotulacionCorrectaRollbacksGp { get; set; }
        public string TiendaTieneTodosPreciadoresColocadosAct { get; set; }
        public string CausasCremasDentales { get; set; }
        public string FallasCremasDentales { get; set; }
        public string CausasCepillosDientes { get; set; }
        public string FallasCepillosDientes { get; set; }
        public string CausasEnjagueBucal { get; set; }
        public string FallasEnjagueBucal { get; set; }
        public string CausasJabonesTocador { get; set; }
        public string FallasJabonesTocador { get; set; }
        public string CausasDesodorantes { get; set; }
        public string FallasDesodorantes { get; set; }
        public string CausasShampoo { get; set; }
        public string FallasShampoo { get; set; }
        public string CausasSuavisantes { get; set; }
        public string FallasSuavisantes { get; set; }
        public string CausasLavaplatos { get; set; }
        public string FallasLavaplatos { get; set; }
        public string CausasDesinfectantes { get; set; }
        public string FallasDesinfectantes { get; set; }
        public string CoCkImpulsoCajalineal { get; set; }
        public string CoCkCpCaJaboncabecera { get; set; }
        public string CpCaOral01cabecera { get; set; }
        public string CpCaOral02cabecera { get; set; }
        public string CpCaRazuradocabecera { get; set; }
        public string CpGbOralgondola { get; set; }
        public string DoCaCloroQuitcabecera { get; set; }
        public string DoCaLabaplatoscabecera { get; set; }
        public string DoCaLimpiadDesinfectcabecera { get; set; }
        public string DoIsCloroisla { get; set; }
        public string CpCremaDentEnjuagueacabecera { get; set; }
        public string CpCremadentEnjuaguealineal { get; set; }
        public string CpCremadentEnjuagueBCabecera { get; set; }
        public string CpJabonLiqCremaDentACabecera { get; set; }
        public string CpCremaDentEnjuagueBLineal { get; set; }
        public string CpJabonLiqCremaDentALineal { get; set; }
        public string CpJabonLiqCremaDentBCabecera { get; set; }
        public string CpJabonLiqCremaDentBLineal { get; set; }
        public string DoCloroDesinfectBCabecera { get; set; }
        public string DoDetergenteDetLiqBCabecera { get; set; }
        public string DoDetergenteDetLiqBLineal { get; set; }
        public string DoIsSuavisanteDetLiqCabecera { get; set; }
        public string DoIsSuavisanteDetLiqLineal { get; set; }
        public string DoIsSuavisanteDetLiqIsla { get; set; }
        public string DoLimpiadLavaplatosBCabecera { get; set; }
        public string DoLimpiadLavaplatosBLineal { get; set; }
        public string ImpulsosCajasCoRetoEnCajas { get; set; }
        public string CoCkImpulsoCajaProductos { get; set; }
        public string CpCaJabonProductos { get; set; }
        public string CpCaOral01Productos { get; set; }
        public string CpCaOral02Productos { get; set; }
        public string CpCaRazuradoProductos { get; set; }
        public string CpGbOralProductos { get; set; }
        public string DoCaCloroQuitProductos { get; set; }
        public string DoCaLavaplatosProductos { get; set; }
        public string DoCaLimpiadDesinfectProductos { get; set; }
        public string DoIsCloroProductos { get; set; }
        public string CpCremaDentEnjuagueACabProd { get; set; }
        public string CpCremaDentEnjuagueALinProd { get; set; }
        public string CpCremaDentEnjuagueBCabProd { get; set; }
        public string CpJabonLiqCremaDentACabProd { get; set; }
        public string CpJabonLiqCremaDentALinProd { get; set; }
        public string CpJabonLiqCremaDentBCabProd { get; set; }
        public string CpJabonLiqCremaDentBLiqProd { get; set; }
        public string DoCloroDesinfectBCabProd { get; set; }
        public string DoDetergenteDetLiqBCabProd { get; set; }
        public string DoDetergenteDetLiqBLinProd { get; set; }
        public string DoIsSuavizanteDetLiqCabProd { get; set; }
        public string DoIsSuavizanteDetLiqLinProd { get; set; }
        public string DoLimpiadLavaplatosBCabProd { get; set; }
        public string DoLimpiadLavaplatosBLinProd { get; set; }
        public string ImpulsosCajasCoRetoEnCajasProd { get; set; }
        public string CpCremaDentEnjuagueBLinProd { get; set; }
        public string DoIsSuavizanteDetLiqIslaProd { get; set; }
        public string ProductosCHogarDesinfectantes { get; set; }
        public string ProductosCHogarLavaplatos { get; set; }
        public string Gestiones { get; set; }
        public string FaltantesCepillosDeDientes { get; set; }
        public string FaltantesCremasDentales { get; set; }
        public string FaltantesEnjuaguesBucales { get; set; }
        public string FaltantesDesodorantes { get; set; }
        public string FaltantesJabonesDeTocador { get; set; }
        public string FaltantesShampoos { get; set; }
        public string FaltantesSuavisantes { get; set; }
        public string FaltantesLavaplatos { get; set; }
        public string FaltantesDesinfectantes { get; set; }
        public string CantidadIpsGestionadas { get; set; }
        public string CaCp1Cabecera { get; set; }
        public string CaCp1CabeceraProductos { get; set; }
        public string CaHp4Cabecera { get; set; }
        public string CaLr1Cabecera { get; set; }
        public string CaLr1Productos { get; set; }
        public string Isp10IslaPrimaria { get; set; }
        public string Isp10Productos { get; set; }
        public string Isp16IslaPrimaria { get; set; }
        public string Isp16Productos { get; set; }
        public string Iss2IslaSecundaria { get; set; }
        public string Reto01RetoEnCaja { get; set; }
        public string Reto01Productos { get; set; }
        public string TabTab { get; set; }
        public string TabProductos { get; set; }
        public string CaHp4Productos { get; set; }
        public string Iss2Productos { get; set; }
        public string CaLh1Cabecera { get; set; }
        public string CaLh1Productos { get; set; }
        public string CaCo3Cabecera { get; set; }
        public string CaCo3Productos { get; set; }
        public string CaTemp2Cabecera { get; set; }
        public string CaTemp2Productos { get; set; }
        public string CoSkProveedor3Cabecera { get; set; }
        public string CoSkProveedor3Productos { get; set; }
        public string LinealLineal { get; set; }
        public string LinealPrpductos { get; set; }
        public string PlCaCo3Cabecera { get; set; }
        public string PlCaCo3Productos { get; set; }
        public string PlLateral9Lateral { get; set; }
        public string PlLateral9LateralProductos { get; set; }
        public string Reto01RetoEnCajas { get; set; }
        public string Reto01RetoEnCProductos { get; set; }
    }
}
